# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d49857bd69f68f2e6f91c3403ea23e651c3a6597fa20de23603308dc0279ac9e522bc9aa61573cddb7906c33b94604b8e4666633a349853385572d959544a474

test:
  secret_key_base: f303638ce1ece069b915937fe9c28bafd6fea5061b5a390e23e568ec5461986e7e0d962e3994f40185ac917fbdb80560a6d26dda2dfd9573aed879be2a6fc9e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
